# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MonoHelix Labs
email: contact@monohelix.com
description: > # this means to ignore newlines until "baseurl:"
  Blog posts from MonoHelix Labs. We try out new technologies, geek around, have fun, and share our knowledge.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://labs.monohelix.com" # the base hostname & protocol for your site
twitter_username: monohelixlabs
github_username:  monohelixlabs

# Build settings
markdown: kramdown
